[project]
name = "hydra-strategy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.30.1",
    "lumibot>=3.6.5",
    "snakeviz>=2.2.2",
    "yappi>=1.6.10",
]
